name: hots_dog_api
description: API calls for the hots.dog Heres of Storm API
version: 1.0.3
homepage: https://github.com/arranf/hots.dog-API
authors:
  - Arran France <arranf@gmail.com>

environment:
  sdk: '>=1.24.2'

dependencies:
  http: ^0.11.3+13
  collection: ^1.14.3