name: hots_dog_api
description: Library to use the hots.dog api
version: 0.0.1
homepage: https://github.com/arranf/hots_dog_api
authors:
  - Arran France <arranf@gmail.com>

environment:
  sdk: '>=1.24.2'

dependencies:
  http: ^0.11.3+13